import { css } from '@emotion/react'
import Head from 'next/head'
import React from 'react'
import MissionContainer from '../components/about/mission'
import Layout from '../components/layout'

const about = () => {
  return (
    <Layout>
      <Head>
        <title>🎂 케이크크</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        css={css`
          margin: auto;
          /* width: 60.25rem; */
        `}
      >
        <MissionContainer />
      </main>
    </Layout>
  )
}

export default about
