import { NextPage } from 'next'
import Head from 'next/head'
import BannerContainer from '../components/main/banner'
import Layout from '../components/layout'
import React from 'react'
import { ShopInfoContainer } from '../components/detail/shopinfo-container'

//TODO : 상의후 BannerContainer에 slidesPerView 인자로 넘겨주기
const Detail: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>🎂</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BannerContainer />
      <ShopInfoContainer
        title="을지로 앵초"
        desc="직접 구운 촉촉한 시트와 크림치즈크림을 사용합니다. 케이크예약은 카카오톡채널 “을지로앵초” 디엠X"
      />
    </Layout>
  )
}

export default Detail
