import { NextPage } from "next";
import Head from "next/head";
import React from "react";

const FallInLoveWIthCake: NextPage = () => {
  return (
    <>
      <Head>
        <title>🎂</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>FallInLoveWIthCake</h1>
    </>
  );
};

export default FallInLoveWIthCake;
