import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>🎂 케이크크</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 css={css`background-color: lightpink;`}>🎂 케이크크 </h1>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
