import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import BannerContainer from '../components/main/banner'
import Layout from '../components/layout'
import SeacrhContainer from '../components/main/search/SeacrhContainer'
import RankContainer from '../components/main/rank-section/RankContainer'
import AreaContainer from '../components/main/area-section'
import * as Styled from '../styles/home'
import { CategoryProvider, LocationProvider } from '../context'

import { fetchPopular, PopularResponse } from '../src/api/api'

const Home = ({ data }: { data: PopularResponse[] }) => {
  return (
    <Layout>
      <Head>
        <title>🎂 케이크크</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Styled.Home>
        <LocationProvider>
          <CategoryProvider>
            <BannerContainer />
            <SeacrhContainer />
            <RankContainer data={data} />
            <AreaContainer />
          </CategoryProvider>
        </LocationProvider>
      </Styled.Home>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await fetchPopular()

  return {
    props: { data }, // will be passed to the page component as props
  }
}

export default Home
